#!/bin/bash

set -eu
source $(dirname $0)/../.argfile

export DOCKER_BUILDKIT=1

docker pull ${BASE}

echo "BUILD: ${DOCKER_REPO}:base"
docker pull ${DOCKER_REPO}:base || true
docker build \
    --cache-from ${BASE} \
    --cache-from ${DOCKER_REPO}:base \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    -f ${DOCKERFILE_PATH} \
    --target base \
    --tag ${DOCKER_REPO}:base .
docker push ${DOCKER_REPO}:base


echo "BUILD: ${DOCKER_REPO}:oracle-base"
docker pull ${DOCKER_REPO}:oracle-base || true
docker build \
    --cache-from ${BASE} \
    --cache-from ${DOCKER_REPO}:base \
    --cache-from ${DOCKER_REPO}:oracle-base \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    -f ${DOCKERFILE_PATH} \
    --target oracle-base \
    --tag ${DOCKER_REPO}:oracle-base .
docker push ${DOCKER_REPO}:oracle-base


echo "BUILD: ${DOCKER_REPO}:builder"
docker pull ${DOCKER_REPO}:builder || true
docker build \
    --cache-from ${BASE} \
    --cache-from ${DOCKER_REPO}:base \
    --cache-from ${DOCKER_REPO}:builder \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --build-arg PYTHON_VERSION=${PYTHON_VERSION} \
    --build-arg PYTHON_PIP_VERSION=${PYTHON_PIP_VERSION} \
    -f ${DOCKERFILE_PATH} \
    --target builder \
    --tag ${DOCKER_REPO}:builder .
docker push ${DOCKER_REPO}:builder
